### PR TITLE
User, Posts and Comments records are functional

### PR DESCRIPTION
**Pull request by didymus707**
In this branch. the user can create posts and also write comments. All posts and comments for each user can also be retrieved

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello @didymus707
### You have put in some good effort :clap: However, you have a few issues to dress
- [ ] You need to add routes in the application for users to actually navigate through the app i.e resources :comments, only: %i[create destroy update edit]
- [ ] You need to create actions in the respective controllers i.e post_controller.rb, users_controller.rb
- [ ] You need to create a more detailed readme file
- [x] You also, need to lint the project source code by installing rubocop, run and solve raised issues

### Note - behavior we are looking for is a user can be created, a user can create post, a user can comment on a post
### Make all these changes and resubmit for another code review. Good luck.

By Raymond
slack @iamraymond

**Comment by didymus707** [comment]
The requirement of the project was not to build a front end for it hence the test in our console

**Comment by didymus707** [comment]
No errors were detected when i ran so I don't understand where those failed checks are coming from

**Review by kobiyoyo — CHANGES_REQUESTED** [review]
## Hi @didymus707       
#### Great Job so far, but there are a few more things required. 
### General
- [ ] The title of your readme.md file should be the name of the project you are working on.
- [ ] I can't do the following actions in my console.
#### Behaviour
- [x] A user can be created 
- [x] A post can be created 
- [x]  A comment can be created 
#### [OPTIONAL]
I recommend adding `title` to `post` attributes

### Make changes and submit another code review request.
*Happy coding* 
(Any questions Feel free to contact me on slack @kobiyoyo)

**Comment by didymus707** [comment]
Screenshot from 2020-05-19 17-27-10
Yo man, that is a screenshot above showing posts and comments being created

**Review by Forison — APPROVED** [review]
## Status:: Approved ✔️
# 🙋🏻‍♂️ Orotayo,
#### Good job on addressing the issues raised by my colleagues earlier.
## Go ahead and merge branch and proceed to the next task🚀
#### Happy coding💻
Addo

**Pull request merged**
